[package]
name = "clippy-2022-11-15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-server = { version = "0.5.0", features = [ "tls-rustls"] }